# Mundo 9

### Leitura e extração de dados

In [3]:
import pandas as pd
import os
diretorio_atual = os.getcwd()
os.chdir(diretorio_atual)

In [7]:
# 1. Armazenar todo o conteúdo do CSV em uma string de múltiplas linhas
#    Usamos aspas triplas (""") para isso.
conteudo_csv = """Cotações Diárias dos Bancos Brasileiros - 29/09/2025
TICKER;BANCO;ABERTURA;FECHAMENTO;VOLUME
ITUB4;Itaú Unibanco Holding S.A.;32,50;33,10;52000000
BBDC4;Banco Bradesco S.A.;15,80;16,25;65000000
BBAS3;Banco do Brasil S.A.;58,20;57,90;41000000
SANB11;Santander Brasil S.A.;30,15;30,85;23000000
XPML11;XP Malls FII;115,40;116,10;1500000
BPAC11;BTG Pactual S.A.;35,00;36,50;31000000
ITSA4;Itaúsa S.A.;10,12;10,25;75000000
BIDI11;Banco Inter S.A.;21,50;20,95;18000000
BPAN4;Banco Pan S.A.;8,55;8,75;12000000
ABC Brasil;Banco ABC Brasil S.A.;22,30;22,90;5000000
"""

# 2. Definir o nome do arquivo que será criado
nome_do_arquivo = 'bancos_cotacoes.csv'

# 3. Usar o 'with open()' para criar e escrever no arquivo
#    'w' significa modo de escrita (write). Ele cria o arquivo se não existir.
#    'encoding='utf-8'' é importante para salvar os acentos corretamente.
with open(nome_do_arquivo, 'w', encoding='utf-8') as arquivo:
    arquivo.write(conteudo_csv)

# 4. Mensagem de confirmação (opcional, mas recomendado)
print(f"Arquivo '{nome_do_arquivo}' foi criado com sucesso!")

Arquivo 'bancos_cotacoes.csv' foi criado com sucesso!

In [11]:
dados_bp = pd.read_csv("bancos_cotacoes.csv", sep = ";", encoding = 'utf-8')
#por padrão é virgula, mas como no brasil decimal usa ",", nós usamos ; em arquivos csv. 

dados_bp

                                                          Cotações Diárias dos Bancos Brasileiros - 29/09/2025
TICKER     BANCO                      ABERTURA FECHAMENTO                                             VOLUME
ITUB4      Itaú Unibanco Holding S.A. 32,50    33,10                                                52000000
BBDC4      Banco Bradesco S.A.        15,80    16,25                                                65000000
BBAS3      Banco do Brasil S.A.       58,20    57,90                                                41000000
SANB11     Santander Brasil S.A.      30,15    30,85                                                23000000
XPML11     XP Malls FII               115,40   116,10                                                1500000
BPAC11     BTG Pactual S.A.           35,00    36,50                                                31000000
ITSA4      Itaúsa S.A.                10,12    10,25                                                75000000
BIDI11     Banco Inter S.A.           21,50    20,95                                                18000000
BPAN4      Banco Pan S.A.             8,55     8,75                                                 12000000
ABC Brasil Banco ABC Brasil S.A.      22,30    22,90                                                 5000000

In [19]:
dados_bp = pd.read_csv("bancos_cotacoes.csv", 
                       sep = ";",
                       skiprows=1, 
                       encoding = 'utf-8',
                       decimal = ",")

dados_bp

       TICKER                       BANCO  ABERTURA  FECHAMENTO    VOLUME
0       ITUB4  Itaú Unibanco Holding S.A.     32.50       33.10  52000000
1       BBDC4         Banco Bradesco S.A.     15.80       16.25  65000000
2       BBAS3        Banco do Brasil S.A.     58.20       57.90  41000000
3      SANB11       Santander Brasil S.A.     30.15       30.85  23000000
4      XPML11                XP Malls FII    115.40      116.10   1500000
5      BPAC11            BTG Pactual S.A.     35.00       36.50  31000000
6       ITSA4                 Itaúsa S.A.     10.12       10.25  75000000
7      BIDI11            Banco Inter S.A.     21.50       20.95  18000000
8       BPAN4              Banco Pan S.A.      8.55        8.75  12000000
9  ABC Brasil       Banco ABC Brasil S.A.     22.30       22.90   5000000

In [21]:
# Verificando os tipos de dados (ABERTURA e FECHAMENTO devem ser float)
print(dados_bp.info())

# Calculando a variação percentual
dados_bp['VARIACAO_%'] = ((dados_bp['FECHAMENTO'] / dados_bp['ABERTURA']) - 1) * 100
dados_bp

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   TICKER      10 non-null     object
 1   BANCO       10 non-null     object
 2   ABERTURA    10 non-null     float64
 3   FECHAMENTO  10 non-null     float64
 4   VOLUME      10 non-null     int64
 5   VARIACAO_%  10 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 608.0+ bytes
None

,TICKER,BANCO,ABERTURA,FECHAMENTO,VOLUME,VARIACAO_%
0,ITUB4,Itaú Unibanco Holding S.A.,32.50,33.10,52000000,1.846154
1,BBDC4,Banco Bradesco S.A.,15.80,16.25,65000000,2.848101
2,BBAS3,Banco do Brasil S.A.,58.20,57.90,41000000,-0.515464
3,SANB11,Santander Brasil S.A.,30.15,30.85,23000000,2.321725
4,XPML11,XP Malls FII,115.40,116.10,1500000,0.606586
5,BPAC11,BTG Pactual S.A.,35.00,36.50,31000000,4.285714
6,ITSA4,Itaúsa S.A.,10.12,10.25,75000000,1.284585
7,BIDI11,Banco Inter S.A.,21.50,20.95,18000000,-2.558140
8,BPAN4,Banco Pan S.A.,8.55,8.75,12000000,2.339181
9,ABC Brasil,Banco ABC Brasil S.A.,22.30,22.90,5000000,2.690583

In [ ]:
dados_bp = pd.read_csv("dfp_cia_aberta_BPP_con_2021.csv", 
                       sep = ";", 
                       encoding = 'ISO-8859-1',
                      decimal = ",",
                      index_col = "DT_REFER",
                      usecols = ['DT_REFER', 'DENOM_CIA', 'ESCALA_MOEDA',
                                'ORDEM_EXERC', 'CD_CONTA', 'DS_CONTA', 'VL_CONTA'])

dados_bp

,DENOM_CIA,ESCALA_MOEDA,ORDEM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA
DT_REFER,,,,,,
2021-12-31,BCO BRASIL S.A.,MIL,PENÚLTIMO,2,Passivo Total,1693794003.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,ÚLTIMO,2,Passivo Total,1899340511.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,PENÚLTIMO,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,3098315.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,ÚLTIMO,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,2053161.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,PENÚLTIMO,2.02,Passivos Financeiros ao Custo Amortizado,1500172488.0000000000
...,...,...,...,...,...,...
2021-12-31,DEXCO S.A.,MIL,ÚLTIMO,2.03.07,Ajustes Acumulados de Conversão,0.0000000000
2021-12-31,DEXCO S.A.,MIL,PENÚLTIMO,2.03.08,Outros Resultados Abrangentes,0.0000000000
2021-12-31,DEXCO S.A.,MIL,ÚLTIMO,2.03.08,Outros Resultados Abrangentes,0.0000000000
2021-12-31,DEXCO S.A.,MIL,PENÚLTIMO,2.03.09,Participação dos Acionistas Não Controladores,1512.0000000000
2021-12-31,DEXCO S.A.,MIL,ÚLTIMO,2.03.09,Participação dos Acionistas Não Controladores,1330.0000000000

In [ ]:
#como transformar dados para CSV? 

df_teste = pd.DataFrame({"empresa": ['WEGE3', 'PCAR4', 'PETR4'],
                       "cotacao": [20, 30, 40]}, index = pd.date_range("2022-01-01", periods = 3))

df_teste

           empresa  cotacao
2022-01-01   WEGE3       20
2022-01-02   PCAR4       30
2022-01-03   PETR4       40

In [ ]:
df_teste.to_csv("teste_df.csv", sep = ";")

# Exercícios

* Exercício 58: Leia o CSV disponibilizado na aula, contendo informações da DRE das empresas da bolsa brasileira em 2021. Utilize as mesmas colunas utilizadas na leitura do balanço patrimonial passivo.

In [ ]:
#gabarito 58

dados_dre = pd.read_csv("dfp_cia_aberta_DRE_con_2021.csv", 
                       sep = ";", 
                       encoding = 'ISO-8859-1',
                      decimal = ",",
                      index_col = "DT_REFER",
                      usecols = ['DT_REFER', 'DENOM_CIA', 'ESCALA_MOEDA',
                                'ORDEM_EXERC', 'CD_CONTA', 'DS_CONTA', 'VL_CONTA'])

dados_dre

,DENOM_CIA,ESCALA_MOEDA,ORDEM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA
DT_REFER,,,,,,
2021-12-31,BCO BRASIL S.A.,MIL,PENÚLTIMO,3.01,Receitas de Intermediação Financeira,98659704.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,ÚLTIMO,3.01,Receitas de Intermediação Financeira,125947217.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,PENÚLTIMO,3.01.01,Receita de Juros,98659704.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,ÚLTIMO,3.01.01,Receita de Juros,125947217.0000000000
2021-12-31,BCO BRASIL S.A.,MIL,PENÚLTIMO,3.02,Despesas de Intermediação Financeira,-43232120.0000000000
...,...,...,...,...,...,...
2021-12-31,DEXCO S.A.,MIL,ÚLTIMO,3.99.01.01,ON,2.4903000000
2021-12-31,DEXCO S.A.,MIL,PENÚLTIMO,3.99.02,Lucro Diluído por Ação,0.0000000000
2021-12-31,DEXCO S.A.,MIL,ÚLTIMO,3.99.02,Lucro Diluído por Ação,0.0000000000
2021-12-31,DEXCO S.A.,MIL,PENÚLTIMO,3.99.02.01,ON,0.6532000000
2021-12-31,DEXCO S.A.,MIL,ÚLTIMO,3.99.02.01,ON,2.4754000000

In [ ]:
import pandas as pd
import numpy as np

def gerar_e_salvar_cotacoes_bancos(nome_arquivo: str):
    """
    Gera dados fictícios de cotações para bancos brasileiros e salva em um arquivo CSV.

    Args:
        nome_arquivo (str): O nome do arquivo CSV a ser criado (ex: 'cotacoes.csv').
    """
    # Passo 1: Definir os tickers e nomes dos bancos
    bancos = {
        'TICKER': ['ITUB4', 'BBDC4', 'BBAS3', 'SANB11', 'BPAC11', 'ITSA4', 'BPAN4', 'ABCB4'],
        'BANCO': ['Itaú Unibanco', 'Bradesco', 'Banco do Brasil', 'Santander Brasil', 
                  'BTG Pactual', 'Itaúsa', 'Banco Pan', 'Banco ABC Brasil']
    }
    num_bancos = len(bancos['TICKER'])

    # Passo 2: Gerar dados numéricos fictícios com NumPy
    # Preços entre 10 e 60
    np.random.seed(42)
    precos_abertura = np.random.uniform(10, 60, num_bancos)
    # Criar alguma variação para os outros preços
    precos_minima = precos_abertura - np.random.uniform(0, 0.5, num_bancos)
    precos_maxima = precos_abertura + np.random.uniform(0, 1, num_bancos)
    precos_fechamento = (precos_minima + precos_maxima) / 2
    # Volume de negociação
    volumes = np.random.randint(5_000_000, 80_000_000, num_bancos)

    # Passo 3: Montar o DataFrame do Pandas
    df_cotacoes = pd.DataFrame({
        'DATA': pd.to_datetime('today').strftime('%Y-%m-%d'),
        'TICKER': bancos['TICKER'],
        'BANCO': bancos['BANCO'],
        'ABERTURA': precos_abertura,
        'MAXIMA': precos_maxima,
        'MINIMA': precos_minima,
        'FECHAMENTO': precos_fechamento,
        'VOLUME': volumes
    })

    # Passo 4: Usar o .to_csv() com parâmetros específicos
    print(f"Gerando o arquivo '{nome_arquivo}'...")
    
    df_cotacoes.to_csv(
        nome_arquivo,
        sep=';',
        index=False,
        decimal=',',
        encoding='utf-8-sig',
        float_format='%.2f'
    )
    
    print(f"Arquivo '{nome_arquivo}' salvo com sucesso!")
    
    return df_cotacoes

Gerando o arquivo 'cotacoes_bancos_b3.csv'...
Arquivo 'cotacoes_bancos_b3.csv' salvo com sucesso!

Pré-visualização do DataFrame gerado:
         DATA  TICKER             BANCO   ABERTURA     MAXIMA     MINIMA  \
0  2025-09-29   ITUB4     Itaú Unibanco  25.946161  26.620160  25.823668
1  2025-09-29   BBDC4          Bradesco  48.786313  49.188294  48.312253
2  2025-09-29   BBAS3   Banco do Brasil  15.679374  15.779388  15.489969
3  2025-09-29  SANB11  Santander Brasil  27.032281  27.518335  26.975234
4  2025-09-29  BPAC11       BTG Pactual  29.256315  29.553048  29.177048

   FECHAMENTO    VOLUME
0   26.221914  51914389
1   48.750273  63206739
2   15.634679  27294737
3   27.246785  79200087
4   29.365048  34363392

In [26]:
# --- Exemplo de como usar a função ---
if __name__ == '__main__':
    df_gerado = gerar_e_salvar_cotacoes_bancos('cotacoes_bancos_b3.csv')
    print("\nPré-visualização do DataFrame gerado:")
    print(df_gerado.head())

Gerando o arquivo 'cotacoes_bancos_b3.csv'...
Arquivo 'cotacoes_bancos_b3.csv' salvo com sucesso!

Pré-visualização do DataFrame gerado:
         DATA  TICKER             BANCO   ABERTURA     MAXIMA     MINIMA  \
0  2025-09-29   ITUB4     Itaú Unibanco  50.369987  50.408885  49.895533
1  2025-09-29   BBDC4          Bradesco  52.826051  52.830933  52.752286
2  2025-09-29   BBAS3   Banco do Brasil  15.785110  16.181348  15.670900
3  2025-09-29  SANB11  Santander Brasil  35.994144  36.116872  35.605953
4  2025-09-29  BPAC11       BTG Pactual  29.928972  30.561591  29.817661

   FECHAMENTO    VOLUME
0   50.152209  64356426
1   52.791610  73045595
2   15.926124  29240927
3   35.861412  36293412
4   30.189626  46926057

# Volume 10

Ok, nós já sabemos ler dados de planilhas. Mas como puxar dados de internet, de cotações das empresas, economias no mundo e muito mais? Na próxima aula nós veremos!