### O sqlite3
- https://docs.python.org/3/library/sqlite3.html
- Vamos tratar uma base fictícia de alunos da Hashtag
- A base já está disponível em:
    - BaseDados.db
    - https://drive.google.com/file/d/12myCVaqez4kE-ZkCtHQjfDK7MDOxbmTj/view?usp=sharing

In [1]:
# Criando a conexão
import sqlite3
con = sqlite3.connect('BaseDados.db')

In [2]:
# Criando um cursor
cur = con.cursor()

In [3]:
# Buscando todas as informações da tabela
cur.execute('SELECT * FROM dados').fetchall()

[(0,
  1,
  'Maria Eduarda da Rocha',
  38273,
  'maria@hashtag.com',
  0,
  1,
  12,
  1,
  1,
  9.0),
 (1, 2, 'Bárbara da Cunha', 63546, 'barbara@hashtag.com', 0, 1, 2, 1, 1, 10.0),
 (2, 3, 'Kevin Melo', 80515, 'kevin@hashtag.com', 1, 1, 3, 1, 1, 7.0),
 (3,
  4,
  'Pedro Henrique da Costa',
  68004,
  'pedro@hashtag.com',
  1,
  1,
  1,
  1,
  1,
  4.0),
 (4, 5, 'Mirella Viana', 28421, 'mirella@hashtag.com', 1, 1, 1, 1, 1, 7.0),
 (5, 6, 'Lívia Jesus', 22284, 'lívia@hashtag.com', 0, 1, 14, 1, 1, 8.0),
 (6, 7, 'Lara Lopes', 38362, 'lara@hashtag.com', 1, 1, 1, 1, 0, None),
 (7, 8, 'Lucca Cardoso', 45109, 'lucca@hashtag.com', 1, 1, 3, 1, 0, None),
 (8, 9, 'Isabelly Souza', 31859, 'isabelly@hashtag.com', 1, 1, 3, 1, 1, 7.0),
 (9, 10, 'Cauã Porto', 42674, 'cauã@hashtag.com', 0, 1, 2, 1, 0, None),
 (10, 11, 'Maria Ferreira', 86563, 'maria@hashtag.com', 0, 1, 1, 1, 1, 7.0),
 (11, 12, 'Júlia Pinto', 47086, 'julia@hashtag.com', 1, 1, 2, 1, 1, 6.0),
 (12,
  13,
  'Antônio Azevedo',
  29022,
  'lovedogs@hashtag.com',
  0,
  1,
  14,
  1,
  1,
  6.0),
 (13, 14, 'Laura Melo', 50966, 'laura@hashtag.com', 1, 1, 2, 1, 1, 6.0),
 (14,
  15,
  'Gabriela Costela',
  21262,
  'gabriela@hashtag.com',
  1,
  1,
  2,
  1,
  1,
  8.0),
 (15, 16, 'Eloah Aragão', 65749, 'eloah@hashtag.com', 1, 1, 3, 1, 1, 8.0),
 (16, 17, 'Francisco Pires', 59518, 'x!c0@hashtag.com', 0, 1, 13, 1, 0, None),
 (17,
  18,
  'Bárbara Freitas',
  19442,
  'barbara@hashtag.com',
  0,
  1,
  12,
  1,
  1,
  6.0),
 (18, 19, 'Melissa Ribeiro', 38438, 'melissa@hashtag.com', 1, 1, 3, 1, 1, 9.0),
 (19,
  20,
  'Lavínia Carvalho',
  89428,
  'lavinia@hashtag.com',
  1,
  1,
  1,
  1,
  0,
  None),
 (20,
  1,
  'Maria Eduarda da Rocha',
  38273,
  'maria@hashtag.com',
  0,
  1,
  12,
  2,
  1,
  8.0),
 (21,
  2,
  'Bárbara da Cunha',
  63546,
  'barbara@hashtag.com',
  0,
  1,
  2,
  2,
  0,
  None),
 (22, 3, 'Kevin Melo', 80515, 'kevin@hashtag.com', 1, 1, 3, 2, 0, None),
 (23, 5, 'Mirella Viana', 28421, 'mirella@hashtag.com', 1, 1, 1, 2, 0, None),
 (24, 6, 'Lívia Jesus', 22284, 'lívia@hashtag.com', 0, 1, 14, 2, 0, None),
 (25, 9, 'Isabelly Souza', 31859, 'isabelly@hashtag.com', 1, 1, 3, 2, 0, None),
 (26, 11, 'Maria Ferreira', 86563, 'maria@hashtag.com', 0, 1, 1, 2, 1, 6.0),
 (27, 12, 'Júlia Pinto', 47086, 'julia@hashtag.com', 1, 1, 2, 2, 1, 10.0),
 (28,
  13,
  'Antônio Azevedo',
  29022,
  'lovedogs@hashtag.com',
  0,
  1,
  14,
  2,
  0,
  None),
 (29, 14, 'Laura Melo', 50966, 'laura@hashtag.com', 1, 1, 2, 2, 0, None),
 (30,
  15,
  'Gabriela Costela',
  21262,
  'gabriela@hashtag.com',
  1,
  1,
  2,
  2,
  0,
  None),
 (31, 16, 'Eloah Aragão', 65749, 'eloah@hashtag.com', 1, 1, 3, 2, 1, 6.0),
 (32,
  18,
  'Bárbara Freitas',
  19442,
  'barbara@hashtag.com',
  0,
  1,
  12,
  2,
  1,
  10.0),
 (33, 19, 'Melissa Ribeiro', 38438, 'melissa@hashtag.com', 1, 1, 3, 2, 1, 7.0),
 (34,
  1,
  'Maria Eduarda da Rocha',
  38273,
  'maria@hashtag.com',
  0,
  1,
  12,
  3,
  1,
  6.0),
 (35, 11, 'Maria Ferreira', 86563, 'maria@hashtag.com', 0, 1, 1, 3, 0, None),
 (36, 12, 'Júlia Pinto', 47086, 'julia@hashtag.com', 1, 1, 2, 3, 0, None),
 (37, 16, 'Eloah Aragão', 65749, 'eloah@hashtag.com', 1, 1, 3, 3, 1, 9.0),
 (38,
  18,
  'Bárbara Freitas',
  19442,
  'barbara@hashtag.com',
  0,
  1,
  12,
  3,
  0,
  None),
 (39,
  19,
  'Melissa Ribeiro',
  38438,
  'melissa@hashtag.com',
  1,
  1,
  3,
  3,
  0,
  None),
 (40,
  1,
  'Maria Eduarda da Rocha',
  38273,
  'maria@hashtag.com',
  0,
  1,
  12,
  4,
  0,
  None),
 (41, 16, 'Eloah Aragão', 65749, 'eloah@hashtag.com', 1, 1, 3, 4, 1, 7.0),
 (42, 16, 'Eloah Aragão', 65749, 'eloah@hashtag.com', 1, 1, 3, 5, 0, None)]

In [4]:
# Salvando em um DataFrame do pandas

In [5]:
# Adicionando o nome das colunas ao nosso DataFrame

In [6]:
# Visualizando os resultados

In [7]:
# Obtendo o tamanho da base